version: '3'

services:
   test-db:
    build: .
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgresdb:/var/lib/postgresql/data
volumes:
  postgresdb:
